-- +goose Up
ALTER TABLE smtp ADD COLUMN from_address VARCHAR(255) DEFAULT '';
ALTER TABLE smtp ADD COLUMN username VARCHAR(255) DEFAULT '';
ALTER TABLE smtp ADD COLUMN password VARCHAR(255) DEFAULT '';

-- +goose Down
ALTER TABLE smtp DROP COLUMN IF EXISTS password;
ALTER TABLE smtp DROP COLUMN IF EXISTS username;
ALTER TABLE smtp DROP COLUMN IF EXISTS from_address;
